receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 5s
    timeout: 5s
    api_version: "1.45"

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 70
    spike_limit_percentage: 15
  batch:

exporters:
  otlp_http/victoriametrics:
    compression: gzip
    encoding: proto
    metrics_endpoint: http://victoriametrics:8428/opentelemetry/v1/metrics
    tls:
      insecure: true
  otlp_grpc/victoriatraces:
    endpoint: victoriatraces:4317
    tls:
      insecure: true

connectors:
  span_metrics:
    exclude_dimensions: [collector.instance.id]
    dimensions:
      - name: http.route
    histogram:
      explicit:
        buckets: [0.05s, 0.1s, 0.25s, 0.5s, 1s, 2.5s, 5s, 10s, 15s]

extensions:
  health_check:

service:
  extensions: [ health_check ]
  pipelines:
    metrics:
      receivers: [ otlp, docker_stats, span_metrics ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp_http/victoriametrics ]
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp_grpc/victoriatraces, span_metrics ]
