apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres-ds
    type: postgres
    url: db:5432
    database: ${POSTGRES_DATABASE}
    user: ${POSTGRES_USER_NAME}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: false
    editable: false
